### ISSUE TITLE
add DailyQuestion

### ISSUE THREAD

**Issue by yushimeng** [LeetCode-OpenSource/vscode-leetcode#831] opened 2022-08-16 02:35 UTC
## 🚀 Feature Proposal
很多leetcode用户都在关注每日一题， 以保证自己的代码逻辑思维。增加每日一题可以提高用户粘度
## Motivation

Please outline the motivation for the proposal.

## Contribution

Please describe the solution if you'd like to submit a PR.

**Comment by EricPedley** [comment] 2022-08-18 16:21
Duplicate of #648, unless I'm misunderstanding the proposal. I can't read Chinese so used Google Translate to read the issue description.

**Comment by yushimeng** [comment] 2022-08-19 02:26
sorry about add a  duplicate issue, this issue is same with #648 . Looking forward for your update.

**Closed** 2022-08-19 02:29 UTC
